package AgendaInterface;


/**
* AgendaInterface/Agenda.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Segunda-feira, 12 de Setembro de 2016 15h16min04s BRT
*/

public interface Agenda extends AgendaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Agenda
