package AgendaInterface;


/**
* AgendaInterface/AgendaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Segunda-feira, 12 de Setembro de 2016 15h16min04s BRT
*/

public interface AgendaOperations 
{
  String inserirContato (String nome, String telefone);
  String removerContato (String nome);
  String atualizarContato (String nome, String telefone);
  String consultarContatos ();
  String informarNomeAgenda ();
  void atualizarAgenda (String contatos);
} // interface AgendaOperations
