package AgendaInterface;


/**
* AgendaInterface/AgendaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Segunda-feira, 12 de Setembro de 2016 15h16min04s BRT
*/

public abstract class AgendaPOA extends org.omg.PortableServer.Servant
 implements AgendaInterface.AgendaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("inserirContato", new java.lang.Integer (0));
    _methods.put ("removerContato", new java.lang.Integer (1));
    _methods.put ("atualizarContato", new java.lang.Integer (2));
    _methods.put ("consultarContatos", new java.lang.Integer (3));
    _methods.put ("informarNomeAgenda", new java.lang.Integer (4));
    _methods.put ("atualizarAgenda", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AgendaInterface/Agenda/inserirContato
       {
         String nome = in.read_string ();
         String telefone = in.read_string ();
         String $result = null;
         $result = this.inserirContato (nome, telefone);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // AgendaInterface/Agenda/removerContato
       {
         String nome = in.read_string ();
         String $result = null;
         $result = this.removerContato (nome);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // AgendaInterface/Agenda/atualizarContato
       {
         String nome = in.read_string ();
         String telefone = in.read_string ();
         String $result = null;
         $result = this.atualizarContato (nome, telefone);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // AgendaInterface/Agenda/consultarContatos
       {
         String $result = null;
         $result = this.consultarContatos ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // AgendaInterface/Agenda/informarNomeAgenda
       {
         String $result = null;
         $result = this.informarNomeAgenda ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // AgendaInterface/Agenda/atualizarAgenda
       {
         String contatos = in.read_string ();
         this.atualizarAgenda (contatos);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AgendaInterface/Agenda:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Agenda _this() 
  {
    return AgendaHelper.narrow(
    super._this_object());
  }

  public Agenda _this(org.omg.CORBA.ORB orb) 
  {
    return AgendaHelper.narrow(
    super._this_object(orb));
  }


} // class AgendaPOA
