package AgendaInterface;

/**
* AgendaInterface/ContatoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Terça-feira, 6 de Setembro de 2016 00h34min20s BRT
*/

public final class ContatoHolder implements org.omg.CORBA.portable.Streamable
{
  public AgendaInterface.Contato value = null;

  public ContatoHolder ()
  {
  }

  public ContatoHolder (AgendaInterface.Contato initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AgendaInterface.ContatoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AgendaInterface.ContatoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AgendaInterface.ContatoHelper.type ();
  }

}
