package AgendaInterface;


/**
* AgendaInterface/Contato.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Terça-feira, 6 de Setembro de 2016 00h34min20s BRT
*/

public final class Contato implements org.omg.CORBA.portable.IDLEntity
{
  public String nome = null;
  public String telefone = null;

  public Contato ()
  {
  } // ctor

  public Contato (String _nome, String _telefone)
  {
    nome = _nome;
    telefone = _telefone;
  } // ctor

} // class Contato
