package AgendaInterface;


/**
* AgendaInterface/ContatoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AgendaInterface.idl
* Terça-feira, 6 de Setembro de 2016 00h34min20s BRT
*/

abstract public class ContatoHelper
{
  private static String  _id = "IDL:AgendaInterface/Contato:1.0";

  public static void insert (org.omg.CORBA.Any a, AgendaInterface.Contato that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AgendaInterface.Contato extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nome",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "telefone",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (AgendaInterface.ContatoHelper.id (), "Contato", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AgendaInterface.Contato read (org.omg.CORBA.portable.InputStream istream)
  {
    AgendaInterface.Contato value = new AgendaInterface.Contato ();
    value.nome = istream.read_string ();
    value.telefone = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AgendaInterface.Contato value)
  {
    ostream.write_string (value.nome);
    ostream.write_string (value.telefone);
  }

}
